name: main-wf

env: 
  zaychik: ${{ secrets.zaychik }}
  ZAYCHIK1: ${{ secrets.ZAYCHIK }}

on: push

jobs:
  check_env:
    runs-on: ubuntu-latest

    steps:
      - name: get src
        uses: actions/checkout@v2

      - name: get env
        run: env ; set

      - name: get python
        run: python --version

      - name: get docker-composer
        run: docker-compose --version

      - name: using scret
        run: echo "zaychik" ; echo "$ZAYCHIK1"
